image: python:3.6-alpine


variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

stages:
  - test
  - deploy

before_script:
  - apk update && apk upgrade
  - apk add --no-cache build-base libffi-dev openssl-dev openssh
  - mkdir -p ~/.ssh
  - ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
  - (umask  077 ; echo $SSH_PRIVATE_KEY | base64 -d > ~/.ssh/id_rsa)
  - pip install -r requirements.txt

python_lint:
  # only:
    # refs:
    # - master
    # - schedules
  stage: test
  script:
    - pylint shipup_s3_transfer.py


run_transfer_s3:
  # only:
  #   refs:
  #   - master
  #   - schedules
  stage: deploy
  variables:
    USER: $SFTP_USERNAME
    PASS: $SFTP_PASSWORD
    HOST: $SFTP_HOST
    BUCKET_NAME: $S3_BUCKET_DESTINATION
  script:
    - python3 shipup_s3_transfer.py
