image: python:3.6-alpine

stages:
  - test
  - deploy

before_script:
  - apk update && apk upgrade
  - apk add --no-cache build-base libffi-dev openssl-dev openssh
  - pip install -r requirements.txt

variables:
  PIP_CACHE_DIR: "pip-cache"

cache:
  paths:
    - pip-cache

python_lint:
  only:
    refs:
    - master
    - schedules
  stage: test
  script:
    - pylint shipup_s3_transfer.py


run_transfer_s3:
  only:
    refs:
    - master
    - schedules
  stage: deploy
  variables:
    USER: $SFTP_USERNAME
    PASS: $SFTP_PASSWORD
    HOST: $SFTP_HOST
    BUCKET_NAME: $S3_BUCKET_DESTINATION
  script:
    # - mkdir -p ~/.ssh
    # - ssh-keyscan $SFTP_HOST >> ~/.ssh/known_hosts
    # - (umask  077 ; echo $SSH_PRIVATE_KEY | base64 -d > ~/.ssh/id_rsa)
    - python shipup_s3_transfer.py
    # - rm ~/.ssh/id_rsa
    # - ssh-keygen -R $SFTP_HOST
